# Generated by Django 4.1.7 on 2023-03-13 04:39

from django.db import migrations, models
import djongo.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Face_Detection',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('user_id', models.IntegerField()),
                ('full_name', models.CharField(max_length=150)),
                ('email', models.CharField(blank=True, max_length=150, null=True)),
                ('image', models.TextField()),
                ('created_time', models.CharField(blank=True, max_length=150, null=True)),
            ],
            options={
                'db_table': 'Face_Detection',
            },
        ),
        migrations.CreateModel(
            name='Time',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('user_id', models.CharField(max_length=50)),
                ('time', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Time',
            },
        ),
    ]
